apiVersion: v1
kind: Service
metadata:
  name: holamundo-service
spec:
  type: LoadBalancer # Usa LoadBalancer para obtener una IP pública externa
  selector:
    app: holamundo-node # Coincide con la etiqueta en el Deployment
  ports:
    - protocol: TCP
      port: 80 # El puerto que expone el Service (público)
      targetPort: 8080 # El puerto al que se dirige dentro del Pod (8080)